### ISSUE TITLE
missing stop button

### ISSUE THREAD

**Issue by deepdish1** [jez500/chorus2#1]
Hi ,

When you read a file, you can see pause,backward and forward but no stop button
Can you add that ?
Thanks ,

DeepDish

**Comment by mizaki** [comment]
If you click the thumbnail (next to the >>) you get extended controls with a stop button.

**Comment by jez500** [comment]
Yeah same as how Chorus 1 works with this

**Comment by deepdish1** [comment]
does not work when I play a file locally : only pause and previous and next track !
no linkon the thumbails ( firefox 38)
