### ISSUE TITLE
where are playlists stored and in what format?

### ISSUE THREAD

**Issue by pppov** [jez500/chorus2#104]
I have created playlists in Chorus 2. But when I choose one and select 'play in kodi' from the drop down menu, instead of playing the playlist, the active playlist is emptied. 

I searched for them with 'find|grep' on the Kodi machine, but couldn't find them. They are not in the playlist directory. So, where are the stored and in what format? And why not in the playlist directory on the Kodi machine?

If would like to edit them and move them to the Kodi playlist directory, so I can play them from there.

**Comment by pppov** [comment]
Basically, playlists do not work as expected in Chorus 2.

I cannot switch between playlists in Chorus 2. I can save them, give them a name, etc..., but I cannot open them again to play in Kodi.

Switching between playlists work all right in Chorus by choosing 'add to playlist' or 'replace playlist'. 
(Also: 'add to playlist' has disappeared from the playlist dropdown menu in Chorus 2. Why? This was a cool feature. Add one playlist to another one...)

**Comment by Meth0d007** [comment]
This has been an issue since chorus(1), it seems to be difficult to save chrous2 playlists on the device (to show up as playlists in kodi).
Would be a very nice feature to manage playlists though (wich is very annoying in kodi for music in general).

**Comment by jez500** [comment]
Unless this has changed recently, the API only allows you to interact with either a single audio or video playlist, in fact these playlists are actually a queue more than a playlist as they are cleared if kodi restarts. 

So, Chorus does a workaround. It uses browser local storage as a place to store its custom playlists. This means that the playlists are only available in the browser it was created in. Not ideal but the only option atm.

In the future I would like to add the ability to import/export the playlists (maybe as .m3u) or even better, have Kodi handle this.
