### ISSUE TITLE
Wrong info displayed in playlist

### ISSUE THREAD

**Issue by vssm2008** [jez500/chorus2#107]
I'm not sure how to describe this bug (?), but this is what happens:

I only use Kodi (on a Windows PC) to listen to the 8000+ CDs stored on my NAS. Usually I set it to "Party mode" in the morning and let it run for the day. The playlist in Chorus2 follows the tracks played ... mostly. I don't look at the Chorus2 screen too often, but it happens - maybe once every 2 or 3 days - that the current track in the Chorus2 display is NOT the one played.

There has been no change to the NAS (no CDs added or deleted), so the Kodi music database should be up-to-date. The music played is not in the playlist currently displayed by Chorus2, so my guess is the playlist scrolled too fast and the current song has already dropped off the list. Does that make sense? Or is this a problem with Kodi and not with Chorus2?

**Comment by jez500** [comment]
Hey @vssm2008 This "should" be fixed in 2.0.15
