### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by amilino** [jez500/chorus2#111]
I am unable to play or download video files which are located on my external HDD attached on Raspberry.

Everytime I open streaming or try to download video with Internet browser I receive authentication popup window. After entering credentials again nothing happends.

Library source is directly added from mounted HDD, maybe that's the problem. Do you know any workaround?

Regards,
Alan

**Comment by dernalis** [comment]
The most common issue which match with description is when the source is not longer present in sources.xml file. Then Kodi denies access to the file.
[http://kodi.wiki/view/Webserver#Virtual_File_System_.2Fvfs]
Check the source is present or add a new one: [http://kodi.wiki/view/Adding_video_sources]

**Comment by amilino** [comment]
Source is in xml, I just checked.

**Comment by amilino** [comment]
I have the same problem with Kore application on my Android device. I can't download videos which are located on my external hard drive. Videos on SD card are working.

This is definitely problem with permissions.

**Comment by dernalis** [comment]
Virtual File System is a Kodi feature, not a Chorus2 feature. 
Open a steam window and get the URL from Download link in this page.
Then, change the skin to the default one and try the link by pasting on address bar.
In case there is the same issue with other skin, you should test by removing source without remove content and adding same source again.

**Comment by amilino** [comment]
I removed and added source again and now it's working. Thank you!

All best.
