### ISSUE TITLE
chorus2 add-on doesn't have correct structure

### ISSUE THREAD

**Issue by oquidave** [jez500/chorus2#113]
Hello, am trying to install the zip file (webinterface.kodi.2.0.14.zip) on my kodi 14. But it says "chorus2 add-on doesn't have correct structure"

**Comment by cylix99** [comment]
extract webinterface.kodi.2.0.14.zip from the zip and install from that

**Comment by PeterCodar** [comment]
I have just downloaded the file from https://github.com/jez500/chorus2/blob/master/webinterface.kodi.2.0.14.zip and installed it on my Raspberry Pi with KODI Jarvis 16.1
It worked fine, without manually unpacking it.

**Comment by jez500** [comment]
Yep, as stated above use the webinterface.kodi.2.x.xx.zip, not github's "download zip" button.
