### ISSUE TITLE
Video streaming not working with VLC plugin

### ISSUE THREAD

**Issue by pcbona** [jez500/chorus2#115]
Hello Guys

Im a fan of Chorus. I really appreciate all the effort that has been put into the programming. It looks beautiful. I even bought a beer for the developer. Thats how pleased i am with this addon.

I mostly want to use this addon to stream movies when im not at home. So im only interested into the "local" setting and streaming.
Problem is, none of the videos are working. I installed the VLC plugin but when i start a video, the player just shows up but does not play anthing.

If found another post that said VLC wont play videos that have the wrong mime type. As far as i can see in the sourcecode, it is set correct to application/x-vlc-plugin as soon as i choose VLS from the dropdown.

```
            // Make the VLC player
            if(player == 'vlc'){
                $player = $('<embed>', {
                    "type": "application/x-vlc-plugin",
                    "pluginspage": "http://www.videolan.org",
                    "version": "VideoLAN.VLCPlugin.2",
                    "width": width,
                    "height": height,
                    "target": '/' + src,
                    "id": id
                });
            }
```

I tried it with the firefox addon Launchy to automatically start VLC when i open a popup, but it didnt work. I also installed videocast in chrome, but as the developer pointed out, chrome is not a good choice to stream from chorus. I have all kinds of video files, most of them come in the MKV format.
Strange thing is, before I installed the VLC web plugin, on the popup in HTML5 there was an error saying it cant play this file because of codec or something. Now, it sais: No compatible source was found for this video.

You can test this out yourself if you wanna have a look. connect go http://bonahome.dyndns.org 
Login info to test is chorus for both username and password. Does it work with your browser or is the problem on the server?

I have only forwarded port 8080 to my server, so i havent forwarded the websocket port 9090. I dont know if this is necessary. The problem is existing in my LAN as well. All ports are open here so i dont think the issue is related to websocket.

Thanks and best regards,
Mario

**Comment by pcbona** [comment]
Here i have an image of what it looks like when VLC has loaded:
![vlcnotplaying](https://cloud.githubusercontent.com/assets/21007766/17643303/afde3b5e-6166-11e6-87ea-31d7d96b428f.png)

**Comment by pcbona** [comment]
I just found out that downloading the video doesnt work as well. All videos are affected, no matter what file types they are. So it must be something related that chorus cant access the video files. The library information is saved on a MySQL database in my environment and playing the videos locally works fine.

The download video link looks like this:

http://bonahome.dyndns.org:8080/vfs/smb%3a%2f%2f10.0.0.10%2fxbmc%2fSeries%2fThe%20last%20Airbender%2fBook%201%2fAvatar%20The%20Last%20Airbender%20-%20Book%201%20Water%20-%20S01E01%20-%20The%20Boy%20in%20the%20Iceberg.avi

![15-08-_2016_10-03-27](https://cloud.githubusercontent.com/assets/21007766/17658962/98a840b4-62cf-11e6-8be7-81dfcbec10ab.png)

So i think there is a problem with the SMB path and the local IP within it. I try to use a local DB instead of an SQL version and see if that helps.

**Comment by pcbona** [comment]
I added the whole library locally now. Took over an hour to scrape everything. I can now download the movies, but i still cant stream them. So im getting closer to the problem here.

I made my movies via directory browsing with a htaccess login available. I can copy the link of the video, in VLC go to file -> open stream, paste the movieurl, enter username and password and it begins to stream. When i do the same with the URL from chorus, there is an error message even before im able to logon:

VLC can't open media: http://bonahome.dyndns.org:8080/vfs/E:/XBMC/Series/The%20last%20Airbender/Book%201/Avatar%20The%20Last%20Airbender%20-%20Book%201%20Water%20-%20S01E02%20-%20The%20Avatar%20Returns.avi

Can anyone pls test if it is working with your browser. I really want to find out if the issue is on the client or server side here.

Thanks and best regards,
Mario

**Comment by pcbona** [comment]
I tried it with the DivX Web Player aswell. It gives me the following error message before crashing:

![15-08-_2016_13-34-27](https://cloud.githubusercontent.com/assets/21007766/17663549/987f57b2-62ed-11e6-9fc3-a7532961bcc8.png)

I tried running Kodi as Administrator on my server but this didnt change anything. I tried an MP4 file with edge since this browser should support to stream it (Bones season 2)
Strange thing is, i can see the upload from my server skyrocking as soon as i start streaming, but the image stays dark.

**Comment by jez500** [comment]
Hey @pcbona 

I am giving up with both vlc and divx, both are very unreliable (vlc doesn't work with chrome anymore). There was a bug with mp4 playback in chrome which I have now fixed so most mkv/mp4s should play ok, only supports 2 channel audio though.

Really we have to wait until Kodi supports transcoding before we can have a reliable way of streaming video locally because browser support for codecs is extremely limited.

**Comment by un1versal** [comment]
> Really we have to wait until Kodi supports transcoding before we can have a reliable way of streaming video locally because browser support for codecs is extremely limited.

I would normally agree with this assessment, but where you have media stored in NAS and where the machine is able to play this media as is, locally and directly, this is what should happen or no? Say e.g. on a PC/Mac... Maybe a new Chorus option in future?

**Comment by pcbona** [comment]
Just for anyone wondering, i switched to plex. It supports streaming and transcoding almost any filetype without any browser plugin.
