### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by mizaki** [jez500/chorus2#16]
I'm thinking we can take the raw PO files from Transifex and then use https://github.com/mikeedwards/po2json in the build script to compile them to json.

What do you think?

**Comment by jez500** [comment]
For sure! TBH I am pretty green with js translations so happy to follow your lead on that.

**Comment by driet** [comment]
Hey, I am new to github but not new to translations. Hope this is the right place to chat. ;)
You're saying, there's a german translation, but there's only a "gr"-file in lng. GR is for greek, DE (for deutsch) for German. I could help with a german translation though, if no one else is working on it.
