### ISSUE TITLE
Video/Stream not working

### ISSUE THREAD

**Issue by deepdish1** [jez500/chorus2#2]
Hi ,

I tried several files (large or small) MKV or AVI and the stream function does not kick in.
I also tried the three options :+1:
html 5
or Vlc (the plugin starts to lad but the file never starts)
or divx 5

Test run with Firefox last release and chrome (windows 7x64 and kodi 14.2 under windows 7x64)
PS : note that under chrome, plugins for VLC don t load up

**Comment by mizaki** [comment]
This is a limitation of HTML5 playing (if you require authorisation VLC won't work). The supported container should be considered MP4 with a video codec of x264 and audio of AAC or MP3. If your files aren't that, don't expect them to work. The good news is the GSOC 2015 to add transcoding. After that it should be a much nicer time for video streaming in the browser.

**Comment by jez500** [comment]
bring on transcoding!
