### ISSUE TITLE
Chorus2 wont load any content.

### ISSUE THREAD

**Issue by uNiversaI** [jez500/chorus2#23]
Copied dist folder to addons folder and rename it webinterface.kodi, webiinterface loads but dont get any content loading from Kodi navigating around chrous2 just doesnt seem to display anything but the interface itself.

It shows the loading animation or no animation whatsoever no matter how long you leave it for.
No matter what category your in no content ever loads.

###### Kodi info
Kodi (15.0-BETA2 Git:2015-06-05-0cb3841-dirty). Platform: Linux x86 64-bit
Kodi compiled Jun  5 2015 by GCC 4.8.2 for Linux x86 64-bit version 3.13.11 (199947)
Running on Ubuntu 14.04.2 LTS, kernel: Linux x86 64-bit version 3.13.0-53-generic

###### Browser Firefox 38.0.5

Console log shows a great deal of errors.
http://pastebin.com/raw.php?i=CmyWpD4x

So clearly either this doesnt support Firefox or something is is seriously wrong.

![splash](https://cloud.githubusercontent.com/assets/3521959/8039919/c0a1976c-0e04-11e5-92c6-d27f388daa70.png)
![splash1](https://cloud.githubusercontent.com/assets/3521959/8039921/c29d68f2-0e04-11e5-934f-3f9c3d34546c.PNG)
![splash2](https://cloud.githubusercontent.com/assets/3521959/8039923/c60484e4-0e04-11e5-8582-a509852a7b32.PNG)
![splash3](https://cloud.githubusercontent.com/assets/3521959/8039924/c63d9d1a-0e04-11e5-8495-68cdc6449194.PNG)

**Comment by jez500** [comment]
Pretty sure this is the giveaway: `http://10.10.1.1:9854/addons/webinterface.kodi/jsonrpc [HTTP/1.1 404 Not Found 2ms]` 

Try either:
- setting as the default web interface and accessing via `http://10.10.1.1:9854`
- Or there is now a setting `reverse proxy` that might fix this too

**Comment by uNiversaI** [comment]
> setting as the default web interface and accessing via http://10.10.1.1:9854

Done, (I had set it as the default web interface already) accessing via http://ip/port seems to work... 

Isnt it suppose to work also via http://10.10.1.1:9854/addons/webinterface.kodi/

I get this is development version but it should work right?

**Comment by jez500** [comment]
Technically accessing via /addons/[addon name] works however it isn't the recommended way to do it, there is issues with base paths... Essentially fixing it for this use case breaks it for other use cases. Down the track I might invest some more time in solutions but for now there is more important things on the todo list.

**Comment by uNiversaI** [comment]
Sure of course, It works for Chorus 1 and its the main way I access it dues to having a couple of WIMM versions installed also.

But not a big issue, I can access those via the multi-addon way and Chorus 2 the regular way also.

The most important thing is that it works mostly. as is..

Thank you again.
