### ISSUE TITLE
Cannot get through initial setup

### ISSUE THREAD

**Issue by paulvt** [jez500/chorus2#30]
When starting Chorus2 for the first time, it bails out during setup with the following error:

    TypeError: null is not an object (evaluating 'JSON.parse(localStorage.getItem('config:app-config:local')).data')

or in Chrome:

    Uncaught TypeError: Cannot read property 'data' of null

I assume this is due to the local storage still not having been created, and for that to happen I probably need to get through the setup?  This is rather a chicken-and-the-egg problem.

**Comment by paulvt** [comment]
Indeed, changing line 46375 of `kodi-webinterface.js` from:

    lang = JSON.parse(localStorage.getItem('config:app-config:local')).data.lang || defaultLang;

to just

    lang = defaultLang;

works.  And then going through the settings and saving it removes the need for this change.

**Comment by jez500** [comment]
Hi @paulvt thanks for pointing this one out, should be fixed now.
