### ISSUE TITLE
Latest build wont load

### ISSUE THREAD

**Issue by uNiversaI** [jez500/chorus2#32]
@jez500 After https://github.com/jez500/chorus2/commit/88bdc03fc7b5d5d63528c1da2e497b536b487a08

am using dist folder from https://github.com/jez500/chorus2/commit/535bcce676c5e65bd255521d788b6e8ec849d1c1

It just doesn't load anymore.

Console output below.
http://pastebin.com/raw.php?i=uLVJqDVU

**Comment by jez500** [comment]
Hey @uNiversaI 

I can't replicate this, I have a feeling it might be some dirty data stored in the browser local storage, can you test in another browser or possibly try [clearing your local storage](http://stackoverflow.com/questions/6084099/how-to-view-delete-local-storage-in-firefox)

Also the console outputs help heaps but by default firefox lists all the warnings which make it hard to spot an error, Setting console to only show JS Errors makes it so much easier for me :)

Thanks!

**Comment by jez500** [comment]
@uNiversaI 
We were both right, app failed to start if you had settings saved in local storage, fixed now :)

**Comment by uNiversaI** [comment]
I'll remember to give you only errors from now on.
