### ISSUE TITLE
Settings > Kodi settings arent saved

### ISSUE THREAD

**Issue by un1versal** [jez500/chorus2#33]
Change the setting, > Press SAVE > Navigate away > go back > bingo

**Comment by jez500** [comment]
TBH that is just a placeholder for when the API gives us the ability to change Kodi settings (what you find under the 'system' menu in Kodi).  Last time I checked that functionality hadn't made it to core yet but was in the works. Can't see anything in the API docs, but if it is there, and someone knows how to do it then let me know.

**Comment by uNiversaI** [comment]
Im sure it has was either settings or functions or both already all exposed, checkout https://github.com/MilhouseVH/texturecache.py its already doing stuff like that I think.

**Comment by jez500** [comment]
Possibly, It is a pretty complex thing though with lots of permutations so I really need some docs or a "how it works" ;)  

I'm sure it is not far off.  I might remove that for the moment and replace it with managing addons which is documented http://kodi.wiki/view/JSON-RPC_API/v6#Addons.SetAddonEnabled

**Comment by uNiversaI** [comment]
Ah well documentation is not exactly there for any of it. But if you look at texturecache.py code or ask @MillhouseVH for a tip or two in forums and see what he says.

**Comment by mizaki** [comment]
https://github.com/mizaki/awxi/commit/9c9e61e0a0abe7038548b9328e195f9efb91ca01

I did some fixes after but gives you most of it. If you can read my horrible code ;)

**Comment by jez500** [comment]
done :)
