### ISSUE TITLE
Pressing play no longer works in nightly Kodi versions

### ISSUE THREAD

**Issue by uNiversaI** [jez500/chorus2#34]
This is a Kodi core issue as the default web interface is also affected.

Im reporting this here as well with the faint hope you could help or already know whats causing it... It affects even the default webinterface as mentioned  but Im not using that though it was tested just to make sure it wasnt the addon but core.

Bug report http://trac.kodi.tv/ticket/16129

Thers nothing in web console at all.

**Comment by jez500** [comment]
Thanks, looks like it has been fixed already, I guess that's the fun of nightlies, you never know what might not work next  ;)

**Comment by uNiversaI** [comment]
Yes was fixed yesterday. :)
I only use master builds which I compile myself, as such follow development very closely (or close enough) so my guesses usually right on what breaks what. (more often than not they work better than *stable* releases believe it or not.
In this case I wanted to let you know just in case
