### ISSUE TITLE
Bug: Cant turn off remote by clicking remote button

### ISSUE THREAD

**Issue by un1versal** [jez500/chorus2#39]
Press the remote button to go into remote mode then pressing the remote button again should take you off the remote mode (it use to now doesn't).

![capture](https://cloud.githubusercontent.com/assets/3521959/8765452/7585a460-2e04-11e5-859a-b9b6f9a2c7bf.PNG)

**Comment by jez500** [comment]
Yeah pretty sure I broke this with some of the recent mobile updates, clicking remote now takes you to #remote so clicking it again should do a back action.

**Comment by uNiversaI** [comment]
Yep, that was what it use to do.

**Comment by un1versal** [comment]
This is fixed in build 2.0.10, closing
