### ISSUE TITLE
Bug: Clicking back button has no effect

### ISSUE THREAD

**Issue by un1versal** [jez500/chorus2#40]
While in browse > path> dir

Pressing back does nothing.

![capture](https://cloud.githubusercontent.com/assets/3521959/8824943/8ac262f8-3072-11e5-9a85-9debdc055b1f.PNG)

**Comment by jez500** [comment]
Clicking the word 'back' appears to work but not clicking the image, will look into it.

**Comment by un1versal** [comment]
This is also fixed in 2.0.10, closing here.
