### ISSUE TITLE
Bug: Overlapping text in list when browser window is resized.

### ISSUE THREAD

**Issue by un1versal** [jez500/chorus2#43]
I think this needs no more introductions.

![capture](https://cloud.githubusercontent.com/assets/3521959/8846850/e94aa592-3121-11e5-8ebc-1a8347e879cf.PNG)

**Comment by jez500** [comment]
Haven't got to that page yet :) but probably next on the list of responsive fixes, along with an artist page album listing

**Comment by uNiversaI** [comment]
Of course, Maybe you are aware of half of these issues already or maybe you are not ;) , I'll just line line them all up for you.

**Comment by jez500** [comment]
Keep 'em coming, I like checklists :)

**Comment by uNiversaI** [comment]
The good thing to remember is the important stuff works ;) 

> I like checklists :)

Is that a pencil hung on the ear and clipboard job?

**Comment by jez500** [comment]
fixed
