### ISSUE TITLE
can't install on kodi 15.2

### ISSUE THREAD

**Issue by primaeval** [jez500/chorus2#58]
Remove this line from addon.xml to get the zip file to install on Kodi 15.2
`<extension point="xbmc.gui.webinterface"/>`

**Comment by un1versal** [comment]
I think kodi cant handle legacy extension points at all, easily solved unless gotham support is still desired.

**Comment by webyxdesign** [comment]
I removed the line and it still says "Addon does not have the correct structure".  I use openelec with kodi 15.1

**Comment by un1versal** [comment]
can you try https://github.com/un1versal/chorus2/blob/9fbb04053709e26f1ae90356792ea7c1f5a0a037/webinterface.kodi.zip
