### ISSUE TITLE
Feature Request: Set JSON Enabled Settings from Chrous

### ISSUE THREAD

**Issue by OliPassey** [jez500/chorus2#75]
Many settings (all?) within Kodi can be set by JSON call, could we have a "Kodi Admin" style interface within Chorus to allow remote-administration of Kodi ?

Use case is i managed 7 Kodi Installs all over the UK for various family members, but they aren't techies, i SSH in to admin a lot of the time but exposing the settings menu through a nice web interface would make my life so much easier!

Many Thanks for your consideration

**Comment by jez500** [comment]
You should be able to configure 95% of Kodi settings via Chorus2 (at least what you can do via the Kodi UI). Just click the cog.

What can you not do now, which you would like to?

**Comment by OliPassey** [comment]
I will check im using Chrous2 - not sure i am.
Thanks for quick response!

**Comment by OliPassey** [comment]
Am i going mad?
My Chorus installation is new - cloned from github as suggested in the readme and installed manually
It doesnt look the same as your screenshots, and i have no settings page.

Version in Kodi shows latest 2.0.11 - although within chrous about page it says Version 0.3.9

Not sure whats going on, feels like im on chorus1?
Am i missing something?

**Comment by OliPassey** [comment]
So it turns out im a moron - hadnt selected Chorus2 as the default web server, it was chorus 0.9.3 after all...

Consider the request closed :+1: 
The settings page is exactly what i was after.

Will chuck a donation your way in the next few days.

**Comment by jez500** [comment]
@OliPassey - late response, cheers!
