### ISSUE TITLE
Streaming with WebChimera

### ISSUE THREAD

**Issue by phil-ft** [jez500/chorus2#78]
I found this project called WebChimera which is pretty much VLC inside the browser: http://www.webchimera.org/ 
It looks like a good fit for Chorus, it could possibly replace all the other players since it also supports YouTube. It was made for nw.js and Electron though so I don't know if it would work here.

I also wonder: if this is usable what do you think about displaying video where the fanart is right now? I love Kodi but I find the client clumsy when using the keyboard and mouse. If Chorus could play all kinds of video and audio people could ditch the official Kodi client and instead use the "remote" of the server instance. That way you also don't need to sync the DBs or use emby etc.

PS: I'm really digging Chorus, good stuff!

**Comment by jez500** [comment]
Hi @phil-ft 
I had a look at webchimera but appears to require nodejs to run, which the kodi webserver does not have. The solution is really kodi transcoding, when that is available we'll have a much more solid video streaming experience.

Glad you like!
