### ISSUE TITLE
Add manifest.json to support Android's "Add to Homescreen" feature

### ISSUE THREAD

**Issue by XanderStrike** [jez500/chorus2#79]
See [here](https://developer.chrome.com/multidevice/android/installtohomescreen) for more information on homescreen apps. I've used Chorus this way for a while, but the manifest allows you to add more polish like a custom splashscreen, header colors, etc.

Normally I'd do it myself and open a PR, but Kodi throws `could not read addon description of special://home/addons/webinterface.kodi` when attempting to install from zip once I've added the line to `index.html`. The `addon.xml` files are identical so not sure what I'm doing wrong.

**Comment by jez500** [comment]
Added, feel free to PR with any improvements to it
