### ISSUE TITLE
Live TV and Radio click/EPG

### ISSUE THREAD

**Issue by mizaki** [jez500/chorus2#8]
Clicking the channel (not the play button) takes you to #. Missing EPG page I would presume?

Mentioning EPG would it be better to have PVR as a subsection with "Channels" and "EPG"?

Music
  SECTIONS
    Recent
    Artists
    Albums
  DIGITAL RADIO
    Channels
    Guide

**Comment by jez500** [comment]
Don't think the API supports EPG... http://kodi.wiki/view/JSON-RPC_API/v6#PVR

**Comment by jez500** [comment]
Default action should maybe be play (or nothing)

**Comment by mizaki** [comment]
Sadly that page is out-dated: http://forum.kodi.tv/showthread.php?tid=98551

I've just done a grid view for AWXi so I'll try and knock something together.
