### ISSUE TITLE
Sort album by artist

### ISSUE THREAD

**Issue by StephRun** [jez500/chorus2#84]
when display in SECTION Album
actually its possible to sort by Title/Year/Rating
Why not by Artist ? ;-)
Maybe a suggestion

**Comment by hayesti** [comment]
I would like to see this too. It was the default sorting order of the original Chorus IIRC.

**Comment by jez500** [comment]
Added artist to album sort options

**Comment by StephRun** [comment]
Nice Job  ! Thanks a lot ;-)

Just add FLAC player and its perfect for me  :-)))

Regards

De :  jez500 <notifications@github.com>
Répondre à :  jez500/chorus2 <reply@reply.github.com>
Date :  samedi 27 février 2016 08:22
À :  jez500/chorus2 <chorus2@noreply.github.com>
Cc :  Stéphane Denis <stephane_denis@hotmail.com>
Objet :  Re: [chorus2] Sort album by artist (#84)


Added artist to album sort options
