### ISSUE TITLE
Autoscroll to current playing track

### ISSUE THREAD

**Issue by hayesti** [jez500/chorus2#88]
On opening Chorus2 in the browser, the playlist is displayed from the first entry. If the playlist was made beforehand and has been playing a while, then your current track probably isn't visible by default. Perhaps, on navigating to Chorus2, it could autoscroll to the currently playing track.

I would also suggest having a button somewhere that--when clicked--brings you to the currently playing track. It could be located beside the Kodi and Local tabs. This way it will be easier to find where you are in a potentially long playlist. This would be more elegant than autoscrolling on a track change since the latter may interfere with the user when he or she is manually moving tracks around the playlist.

**Comment by jez500** [comment]
Done, and there is also a setting to toggle the auto scrolling
