### ISSUE TITLE
Music > Artist > Filter by Genre: genre list not showing

### ISSUE THREAD

**Issue by arigit** [jez500/chorus2#90]
Trying to filter the Artist list by Genre: the genre list shows empty 

The genres are in the library and they show fine in Chorus2 when doing Music > Albums > Filter by Genre; in that case the genre entries show up and I can filter the Album list by genre. Unfortunately this is not working when trying to filter the Artist list.

With many hundreds of artists, this issue makes chorus2 usability quite limited

**Comment by jez500** [comment]
Hi @arigit 
I can't replicate this, It works for me.

 Artists and albums have their own genres so it is possible your artists aren't getting updated with the genre but the albums are. Maybe check the "Fetch additional information during updates" setting is enabled.

**Comment by arigit** [comment]
I see, yes definitely my artists do not have genre information, honestly I didn't know that data even existed. All my album metadata comes from Cuesheets (all my collection is FLAC)

My ask is then: is it possible to filter the Artist list by "Album Genre", i.e. all artists that have one or more albums of the selected Genre? Typical use case, this is the most common use when browsing the music library on Kodi's GUI: you select the Genre, then you can get a list of artists, then drill down to the album level.
With 3000 albums and some 500 artists, this would be really useful, and feature parity with what can be done with Kodi GUI.
