### ISSUE TITLE
[SOLVED] Can´t download files

### ISSUE THREAD

**Issue by besgum** [jez500/chorus2#95]
Hi to all, first of all, chorus is a damn nice project.
I really search for information regarding my issue, but I couldnt find anything. 

I´m running chorus 2 on a raspberry 2 with osmc (Kodi 16).

When I press **download** to any serie or movie it just pop up a new windows with a blank page, and nothing happens... this is an example link: **`XXXXXXXX:8090/vfs/%2fmedia%2fexternal%2ftvshows%2fThe%20Walking%20Dead%2fThe.Walking.Dead.S06E11.720p.HDTV.x264-AVS.mkv`**

Also I wasn´t able to stream on browser, I try on chrome and in internet explorer using divx web player... but nothing

But my priority is the download thing, that would be nice to have it working. Hope someone can help me

Sorry for the bad english!

**Comment by dernalis** [comment]
The most common issue which match with description is when the source is not longer present in sources.xml file. Then Kodi denies access to the file.
Check this link [http://kodi.wiki/view/Media_sources](http://kodi.wiki/view/Media_sources)

**Comment by besgum** [comment]
Dernalis, thank you very much for your answer. 
Indeed, I couldn't find the sources.xml on home/osmc/.kodi/userdata.
Kodi it's working well (i'm not using sql), so the question now is... How I can make that file or force kodi to recreate it??  
Why would kodi not create the source.xml?

Thanks for the advice
> The most common issue which match with description is when the source is not longer present in sources.xml file. Then Kodi denies access to the file.
Check this link http://kodi.wiki/view/Media_sources

**Comment by dernalis** [comment]
Welcome. You must add same sources again. If files are already in library you don't need to scan again.
http://kodi.wiki/view/Adding_video_sources

**Comment by besgum** [comment]
dernails it WORKS!!! Thank you very much!
