### ISSUE TITLE
Option to set base path

### ISSUE THREAD

**Issue by cyrusboadway** [jez500/chorus2#97]
I'd love to be able to put kodi behind a reverse proxy: e.g. `myhome.com/kodi`. To do that would require asset requests & ajax/websocket calls to be prepended with a base path. For assets, I think it would be as simple as adding a `<base />` tag. The JS would need to know about the path as well.

**Comment by dernalis** [comment]
Sorry, but not sure why you need it, this config is working for me in apache, even streaming:
```
  <Proxy *>
    Order deny,allow
    Allow from all
  </Proxy>
  AllowEncodedSlashes On
  ProxyPreserveHost On
  ProxyPass /kodi/ http://openelec:8080/ nocanon
  ProxyPassReverse /kodi/ http://openelec:8080/
  SetEnv force-proxy-request-1.0 1
  SetEnv proxy-nokeepalive 1
```
Once I turn on "Reverse proxy support" in Settings->General->Webinterface.

It's also possible to use more complex directives in apache to make it work without enable support in Chorus2.

**Comment by cyrusboadway** [comment]
Awesome. I didn't know that was possible. I'l check it out.

**Comment by muhahacz** [comment]
@dernalis it's not that simple.... basepath is definitely better choice.

You need to proxy also websocket and still then chorus will call non context basepath,
for example http(s)://openelec:proxyport/jsonrpc?
But jsonrpc will be available at http(s)://openelec:proxyport/kodi/jsonrpc?

**Comment by muhahacz** [comment]
RewriteCond %{HTTP_REFERER} ^https?://[^/]+/xbmc
RewriteCond %{REQUEST_URI} !^/xbmc
RewriteCond %{THE_REQUEST} ^GET
RewriteRule ^/(.*) /xbmc/$1 [QSA,R]

RewriteCond %{HTTP_REFERER} ^https?://[^/]+/xbmc
RewriteCond %{REQUEST_URI} !^/xbmc
RewriteCond %{THE_REQUEST} ^POST
RewriteRule ^/(.*) /xbmc/$1 [QSA,PT]

ProxyPass /xbmc/ http://127.0.0.1:8080/
ProxyPassReverse /xbmc/ http://127.0.0.1:8080/
